SELECT
  * EXCEPT(rnk)
FROM (
  SELECT
    *,
    DATE(_PARTITIONTIME) AS EOD_Date,
    ROW_NUMBER() OVER (PARTITION BY INUMBR, ISTORE ORDER BY DATE(_PARTITIONTIME) DESC ) AS rnk
  FROM
    ``
  WHERE
    DATE(_PARTITIONTIME) <= "CURRENT_DATE"
  ) AS a
WHERE
  rnk = 1